spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/81673211/spring-cloud-config-study
          search-paths:
          username:
          password:
      label: master


server:
  port: 8777

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
